### ISSUE TITLE
No path found logs an error

### ISSUE THREAD

**Issue by albertshau** [cdapio/netty-http#15]
If a client attempts to make a request to a path that does not exist, the framework will throw an exception, which gets logged as an error.  In these circumstances, it is not an error in the framework, but an invalid request from a client so it seems like it should not be logged as an error.

**Comment by albertshau** [comment]
An example error message:

```

co.cask.http.HandlerException: Problem accessing: /v2/deploy/status. Reason: Not Found
    at co.cask.http.HttpResourceHandler.getDestinationMethod(HttpResourceHandler.java:257) ~[co.cask.http.netty-http-0.9.0.jar:na]
    at co.cask.http.RequestRouter.handleRequest(RequestRouter.java:114) ~[co.cask.http.netty-http-0.9.0.jar:na]
    at co.cask.http.RequestRouter.messageReceived(RequestRouter.java:83) ~[co.cask.http.netty-http-0.9.0.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[io.netty.netty-3.6.6.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) ~[io.netty.netty-3.6.6.Final.jar:na]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) ~[io.netty.netty-3.6.6.Final.jar:na]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[io.netty.netty-3.6.6.Final.jar:na]
    at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:69) ~[io.netty.netty-3.6.6.Final.jar:na]
    at co.cask.http.NettyHttpService$2.handleUpstream(NettyHttpService.java:230) ~[co.cask.http.netty-http-0.9.0.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[io.netty.netty-3.6.6.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[io.netty.netty-3.6.6.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[io.netty.netty-3.6.6.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109) ~[io.netty.netty-3.6.6.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[io.netty.netty-3.6.6.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[io.netty.netty-3.6.6.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[io.netty.netty-3.6.6.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
    at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
```

**Comment by albertshau** [comment]
moving to jira
