### ISSUE TITLE
@Path("/{keyResources:.*}") throws IllegalArgumentException

### ISSUE THREAD

**Issue by cdancy** [cdapio/netty-http#39]
The `@Path` annotation allows one to use regular expression to denote and catch multiple sub-paths (i.e.. /hello/world/one/two/three through I'm only listening on /hello). I've posted a few stackoverflows below where this is mentioned and shows to work as expected. However, when using this library to do the same I get the below when trying to hit `/v2/keys/bears/fish/monkey`:

```
2016-10-10 20:36:50 [etcd-java-client-worker-thread-1] ERROR co.cask.http.HttpDispatcher - Exception caught in channel processing.
co.cask.http.HandlerException: Error in executing request: GET /v2/keys/bears/fish/monkey
    at co.cask.http.HttpResourceModel.handle(HttpResourceModel.java:144)
    at co.cask.http.HttpResourceHandler.getDestinationMethod(HttpResourceHandler.java:258)
    at co.cask.http.RequestRouter.handleRequest(RequestRouter.java:114)
    at co.cask.http.RequestRouter.messageReceived(RequestRouter.java:83)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
    at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:69)
    at co.cask.http.NettyHttpService$2.handleUpstream(NettyHttpService.java:205)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Could not resolve value for parameter keyResources
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
    at co.cask.http.HttpResourceModel.getPathParamValue(HttpResourceModel.java:166)
    at co.cask.http.HttpResourceModel.handle(HttpResourceModel.java:126)
```

Code snippet:

```
@Path("/{version}/keys")
@Produces(MediaType.APPLICATION_JSON)
@Controller
public class Keys extends AbstractHttpHandler {

    /**
     * Sets a key/value pair
     * 
     * @param request HttpRequest
     * @param responder HttpResponder
     * @param var
     */
    @Named("keys:set")
    @Path("/{keyResources: .*}")
    @GET
    public void setKey(HttpRequest request, HttpResponder responder, @PathParam("keyResources") String keyResources) {...}
```

[Link one](http://stackoverflow.com/questions/2945947/path-and-regular-expression-jersey-rest) and [link two](http://stackoverflow.com/questions/15878193/capture-all-possible-path-parameters-jax-rs-regex) for stackoverflow questions regarding similar use-cases. Any ideas or workarounds you guys suggest?

**Comment by poornachandra** [comment]
netty-http library does not support the JAX-RS regex syntax in `@Path` annotation. To match multiple sub-paths for a path, you can use the following syntax -

```
    @Path("/path/**")
    @GET
    public void setKey(HttpRequest request, HttpResponder responder) {...}
```

The above regex will match all paths like `/path/path1`, `/path/path1/path2`, etc.

**Comment by cdancy** [comment]
@poornachandra that works! Thanks for the point in the right direction.
