### ISSUE TITLE
@Path("/") in handler throws error

### ISSUE THREAD

**Issue by poornachandra** [cdapio/netty-http#4]
```
@GET
@Path("/")
public void test(HttpRequest request, HttpResponder responder) throws Exception {
  responder.sendStatus(HttpResponseStatus.OK);
}
```

---

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:143)
    at java.lang.StringBuilder.setLength(StringBuilder.java:55)
    at co.cask.http.PatternPathRouterWithGroups.add(PatternPathRouterWithGroups.java:89)
    at co.cask.http.HttpResourceHandler.<init>(HttpResourceHandler.java:91)
    at co.cask.http.NettyHttpService.<init>(NettyHttpService.java:151)
    at co.cask.http.NettyHttpService.<init>(NettyHttpService.java:61)
    at co.cask.http.NettyHttpService$Builder.build(NettyHttpService.java:515)

**Comment by poornachandra** [comment]
This was fixed in https://github.com/caskdata/netty-http/pull/42
